# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 492)
        Form.setStyleSheet("QFrame {\n"
                           "    border: none;\n"
                           "}\n"
                           "QFrame#asider {\n"
                           "    background-color: rgb(231, 231, 231);\n"
                           "}\n"
                           "QFrame#asider QPushButton {\n"
                           "    border: none;\n"
                           "    color: rgb(50, 50, 47);\n"
                           "    font-weight: bold;\n"
                           "    font-size: 10pt;\n"
                           "}\n"
                           "QFrame#asider QPushButton:hover {\n"
                           "    color: rgb(255, 255, 255);\n"
                           "    background-color: rgb(97, 97, 97);\n"
                           "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.asider = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.asider.sizePolicy().hasHeightForWidth())
        self.asider.setSizePolicy(sizePolicy)
        self.asider.setMinimumSize(QtCore.QSize(150, 0))
        self.asider.setStyleSheet("")
        self.asider.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.asider.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.asider.setObjectName("asider")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.asider)
        self.verticalLayout_2.setContentsMargins(0, 20, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menuButton_1 = QtWidgets.QPushButton(parent=self.asider)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.menuButton_1.sizePolicy().hasHeightForWidth())
        self.menuButton_1.setSizePolicy(sizePolicy)
        self.menuButton_1.setMinimumSize(QtCore.QSize(0, 30))
        self.menuButton_1.setStyleSheet("")
        self.menuButton_1.setObjectName("menuButton_1")
        self.verticalLayout_2.addWidget(self.menuButton_1)
        self.menuButton_2 = QtWidgets.QPushButton(parent=self.asider)
        self.menuButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.menuButton_2.setStyleSheet("")
        self.menuButton_2.setObjectName("menuButton_2")
        self.verticalLayout_2.addWidget(self.menuButton_2)
        self.menuButton_3 = QtWidgets.QPushButton(parent=self.asider)
        self.menuButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.menuButton_3.setStyleSheet("")
        self.menuButton_3.setObjectName("menuButton_3")
        self.verticalLayout_2.addWidget(self.menuButton_3)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.asider)
        self.main = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setStyleSheet("")
        self.main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main.setObjectName("main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main)
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.main)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Autoseek"))
        self.menuButton_1.setText(_translate("Form", "我的日程"))
        self.menuButton_2.setText(_translate("Form", "我的数据"))
        self.menuButton_3.setText(_translate("Form", "我的项目"))
