# Form implementation generated from reading ui file 'qcresultDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_QcresultDialog(object):
    def setupUi(self, QcresultDialog):
        QcresultDialog.setObjectName("QcresultDialog")
        QcresultDialog.resize(517, 213)
        QcresultDialog.setMinimumSize(QtCore.QSize(517, 0))
        QcresultDialog.setStyleSheet("QFrame#content {\n"
                                     "    background-color: rgb(255, 255, 255);\n"
                                     "    border-radius: 3px;\n"
                                     "}\n"
                                     "QLabel#pidLabel {\n"
                                     "    font-size: 12pt;\n"
                                     "    font-weight: bold;\n"
                                     "    color: rgb(33, 34, 27);\n"
                                     "}\n"
                                     "#label_sds, #label_sec, #label_lal {\n"
                                     "    font-size: 10pt;\n"
                                     "    font-weight: bold;\n"
                                     "    color: rgb(74, 74, 74);\n"
                                     "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(QcresultDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pidLabel = QtWidgets.QLabel(parent=QcresultDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.pidLabel.sizePolicy().hasHeightForWidth())
        self.pidLabel.setSizePolicy(sizePolicy)
        self.pidLabel.setObjectName("pidLabel")
        self.verticalLayout.addWidget(self.pidLabel)
        self.content = QtWidgets.QFrame(parent=QcresultDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(
            self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.content)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_sds = QtWidgets.QLabel(parent=self.frame_2)
        self.label_sds.setObjectName("label_sds")
        self.verticalLayout_2.addWidget(self.label_sds)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.content)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_sec = QtWidgets.QLabel(parent=self.frame_3)
        self.label_sec.setObjectName("label_sec")
        self.verticalLayout_3.addWidget(self.label_sec)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.content)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_lal = QtWidgets.QLabel(parent=self.frame_4)
        self.label_lal.setObjectName("label_lal")
        self.verticalLayout_4.addWidget(self.label_lal)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.content)
        self.frame_5 = QtWidgets.QFrame(parent=QcresultDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(parent=self.frame_5)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_2.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(parent=self.frame_5)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.verticalLayout.addWidget(self.frame_5)

        self.retranslateUi(QcresultDialog)
        self.cancelButton.clicked.connect(QcresultDialog.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(QcresultDialog)

    def retranslateUi(self, QcresultDialog):
        _translate = QtCore.QCoreApplication.translate
        QcresultDialog.setWindowTitle(
            _translate("QcresultDialog", "Qc-results"))
        self.pidLabel.setText(_translate("QcresultDialog", "P00001"))
        self.label_sds.setText(_translate("QcresultDialog", "SDS"))
        self.label_sec.setText(_translate("QcresultDialog", "SEC"))
        self.label_lal.setText(_translate("QcresultDialog", "LAL"))
        self.okButton.setText(_translate("QcresultDialog", "确定"))
        self.cancelButton.setText(_translate("QcresultDialog", "取消"))
