# Form implementation generated from reading ui file 'sourceDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_sourceDialog(object):
    def setupUi(self, sourceDialog):
        sourceDialog.setObjectName("sourceDialog")
        sourceDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        sourceDialog.resize(428, 251)
        self.verticalLayout = QtWidgets.QVBoxLayout(sourceDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=sourceDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.browserButton = QtWidgets.QPushButton(parent=self.frame)
        self.browserButton.setMinimumSize(QtCore.QSize(0, 25))
        self.browserButton.setObjectName("browserButton")
        self.gridLayout.addWidget(self.browserButton, 3, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 3, 4, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(parent=self.frame)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(parent=sourceDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(sourceDialog)
        self.pushButton_2.clicked.connect(sourceDialog.reject)  # type: ignore
        self.pushButton.clicked.connect(sourceDialog.accept)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(sourceDialog)

    def retranslateUi(self, sourceDialog):
        _translate = QtCore.QCoreApplication.translate
        sourceDialog.setWindowTitle(_translate("sourceDialog", "Source"))
        self.label.setText(_translate("sourceDialog", "数据源"))
        self.label_3.setText(_translate("sourceDialog", "默认"))
        self.lineEdit.setText(_translate(
            "sourceDialog", "\\\\192.168.29.200\\f\\service\\0.样品管理部\\01 蛋白库相关\\06 蛋白编号\\00 理化质检-P90000之后在这里查理化质检结果"))
        self.browserButton.setText(_translate("sourceDialog", "..."))
        self.pushButton_6.setText(_translate("sourceDialog", "删除"))
        self.lineEdit_2.setPlaceholderText(_translate("sourceDialog", "文件夹路径"))
        self.label_2.setText(_translate("sourceDialog", "自定义"))
        self.addButton.setText(_translate("sourceDialog", "添加"))
        self.pushButton.setText(_translate("sourceDialog", "确认"))
        self.pushButton_2.setText(_translate("sourceDialog", "取消"))
