# Form implementation generated from reading ui file 'shedule.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Schedule(object):
    def setupUi(self, Shedule):
        Shedule.setObjectName("Shedule")
        Shedule.resize(517, 374)
        Shedule.setStyleSheet("QLabel#title {\n"
                              "    color: rgb(85, 85, 85);\n"
                              "    font-size: 18pt;\n"
                              "    font-weight: bold;\n"
                              "}\n"
                              "QLineEdit {\n"
                              "    background-color: rgb(255, 255, 255);\n"
                              "    border-radius: 2px;\n"
                              "    border: 1px solid rgb(180, 180, 180);\n"
                              "}\n"
                              "QPushButton {\n"
                              "    background-color: rgb(180, 180, 180);\n"
                              "    border-radius:2px;\n"
                              "    padding: 3px;\n"
                              "}\n"
                              "QPushButton:hover {\n"
                              "    color: rgb(255, 255, 255);\n"
                              "    background-color: rgb(120, 120, 120);\n"
                              "}\n"
                              "#settingButton {\n"
                              "    background-color: rgba(255, 255, 255, 0);\n"
                              "}\n"
                              "#settingButton:hover {\n"
                              "    color: rgb(255, 255, 255);\n"
                              "    background-color: rgb(120, 120, 120);\n"
                              "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Shedule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Shedule)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QLabel(parent=self.frame)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.settingButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.settingButton.setIcon(QtWidgets.QApplication.style().standardIcon(
            QtWidgets.QStyle.StandardPixmap.SP_FileDialogListView))
        self.settingButton.setToolTip("设置")
        self.settingButton.setObjectName("settingButton")
        self.horizontalLayout_2.addWidget(self.settingButton)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=Shedule)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.importButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.importButton.setMinimumSize(QtCore.QSize(40, 25))
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_3.addWidget(self.importButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.saveButton.setMinimumSize(QtCore.QSize(40, 25))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.testingButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.testingButton.setMinimumSize(QtCore.QSize(40, 25))
        self.testingButton.setObjectName("testingButton")
        self.horizontalLayout_3.addWidget(self.testingButton)
        self.worktimeButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.worktimeButton.setMinimumSize(QtCore.QSize(40, 25))
        self.worktimeButton.setObjectName("worktimeButton")
        self.horizontalLayout_3.addWidget(self.worktimeButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=Shedule)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(
            self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setToolTip("")
        self.frame_3.setToolTipDuration(1)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.frame_3)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_4.addWidget(self.calendarWidget)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Shedule)
        QtCore.QMetaObject.connectSlotsByName(Shedule)

    def retranslateUi(self, Shedule):
        _translate = QtCore.QCoreApplication.translate
        Shedule.setWindowTitle(_translate("Shedule", "Shedule"))
        self.title.setText(_translate("Shedule", "我的日程"))
        self.importButton.setText(_translate("Shedule", "导入"))
        self.saveButton.setText(_translate("Shedule", "保存"))
        self.testingButton.setText(_translate("Shedule", "实验记录"))
        self.worktimeButton.setText(_translate("Shedule", "工时"))
