# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settingDialog(object):
    def setupUi(self, settingDialog):
        settingDialog.setObjectName("settingDialog")
        settingDialog.resize(330, 585)
        settingDialog.setStyleSheet("QGroupBox#personalPanel {\n"
"    font-weight: bold;\n"
"}\n"
"QGroupBox#recordPanel {\n"
"    color: rgb(0, 85, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QGroupBox#worktimePanel {\n"
"    color: rgb(0, 170, 127);\n"
"    font-weight: bold;\n"
"}\n"
"QGroupBox#consumablesPanel, QGroupBox#reagentPanel {\n"
"    font-family: 微软雅黑;\n"
"    font-weight: 600;\n"
"}\n"
"QLineEdit {\n"
"    border-radius: 2px;\n"
"    height:20px;\n"
"}\n"
"QLabel {\n"
"    color: rgb(62, 62, 62);\n"
"    font-family: 微软雅黑;\n"
"    height:20px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(settingDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.personalPanel = QtWidgets.QGroupBox(parent=settingDialog)
        self.personalPanel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.personalPanel.setObjectName("personalPanel")
        self.gridLayout = QtWidgets.QGridLayout(self.personalPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.personalPanel)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(parent=self.personalPanel)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.personalPanel)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.chromeLineEdit = QtWidgets.QLineEdit(parent=self.personalPanel)
        self.chromeLineEdit.setText("")
        self.chromeLineEdit.setObjectName("chromeLineEdit")
        self.gridLayout.addWidget(self.chromeLineEdit, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.personalPanel)
        self.recordPanel = QtWidgets.QGroupBox(parent=settingDialog)
        self.recordPanel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.recordPanel.setObjectName("recordPanel")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.recordPanel)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.consumablesPanel = QtWidgets.QGroupBox(parent=self.recordPanel)
        self.consumablesPanel.setObjectName("consumablesPanel")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.consumablesPanel)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ni_batchLineEdit = QtWidgets.QLineEdit(parent=self.consumablesPanel)
        self.ni_batchLineEdit.setObjectName("ni_batchLineEdit")
        self.gridLayout_4.addWidget(self.ni_batchLineEdit, 1, 1, 1, 1)
        self.pa_akta_batchLineEdit = QtWidgets.QLineEdit(parent=self.consumablesPanel)
        self.pa_akta_batchLineEdit.setObjectName("pa_akta_batchLineEdit")
        self.gridLayout_4.addWidget(self.pa_akta_batchLineEdit, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.consumablesPanel)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.consumablesPanel)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.consumablesPanel)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.pa_batchLineEdit = QtWidgets.QLineEdit(parent=self.consumablesPanel)
        self.pa_batchLineEdit.setText("")
        self.pa_batchLineEdit.setObjectName("pa_batchLineEdit")
        self.gridLayout_4.addWidget(self.pa_batchLineEdit, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.consumablesPanel)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.ni_akta_batchLineEdit = QtWidgets.QLineEdit(parent=self.consumablesPanel)
        self.ni_akta_batchLineEdit.setObjectName("ni_akta_batchLineEdit")
        self.gridLayout_4.addWidget(self.ni_akta_batchLineEdit, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.consumablesPanel, 3, 0, 1, 2)
        self.record_passwordLineEdit = QtWidgets.QLineEdit(parent=self.recordPanel)
        self.record_passwordLineEdit.setInputMask("")
        self.record_passwordLineEdit.setText("")
        self.record_passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.record_passwordLineEdit.setObjectName("record_passwordLineEdit")
        self.gridLayout_2.addWidget(self.record_passwordLineEdit, 1, 1, 1, 1)
        self.record_usernameLineEdit = QtWidgets.QLineEdit(parent=self.recordPanel)
        self.record_usernameLineEdit.setObjectName("record_usernameLineEdit")
        self.gridLayout_2.addWidget(self.record_usernameLineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.recordPanel)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.recordPanel)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.reagentPanel = QtWidgets.QGroupBox(parent=self.recordPanel)
        self.reagentPanel.setObjectName("reagentPanel")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.reagentPanel)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(parent=self.reagentPanel)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.bufferLineEdit = QtWidgets.QLineEdit(parent=self.reagentPanel)
        self.bufferLineEdit.setObjectName("bufferLineEdit")
        self.gridLayout_5.addWidget(self.bufferLineEdit, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.reagentPanel, 4, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(parent=self.recordPanel)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.srcpathLineEdit = QtWidgets.QLineEdit(parent=self.recordPanel)
        self.srcpathLineEdit.setObjectName("srcpathLineEdit")
        self.gridLayout_2.addWidget(self.srcpathLineEdit, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.recordPanel)
        self.worktimePanel = QtWidgets.QGroupBox(parent=settingDialog)
        self.worktimePanel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.worktimePanel.setObjectName("worktimePanel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.worktimePanel)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(parent=self.worktimePanel)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.worktime_passwordLineEdit = QtWidgets.QLineEdit(parent=self.worktimePanel)
        self.worktime_passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.worktime_passwordLineEdit.setObjectName("worktime_passwordLineEdit")
        self.gridLayout_3.addWidget(self.worktime_passwordLineEdit, 1, 1, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.worktimePanel)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 2, 1, 1, 1)
        self.worktime_usernameLineEdit = QtWidgets.QLineEdit(parent=self.worktimePanel)
        self.worktime_usernameLineEdit.setObjectName("worktime_usernameLineEdit")
        self.gridLayout_3.addWidget(self.worktime_usernameLineEdit, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.worktimePanel)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.worktimePanel)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.worktimePanel)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.worktimePanel)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.worktimePanel)
        self.frame = QtWidgets.QFrame(parent=settingDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(settingDialog)
        self.pushButton.clicked.connect(settingDialog.accept) # type: ignore
        self.pushButton_2.clicked.connect(settingDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(settingDialog)

    def retranslateUi(self, settingDialog):
        _translate = QtCore.QCoreApplication.translate
        settingDialog.setWindowTitle(_translate("settingDialog", "setting"))
        self.personalPanel.setTitle(_translate("settingDialog", "个人信息"))
        self.label.setText(_translate("settingDialog", "姓名"))
        self.nameLineEdit.setPlaceholderText(_translate("settingDialog", "中文姓名"))
        self.label_14.setText(_translate("settingDialog", "Chrome"))
        self.chromeLineEdit.setPlaceholderText(_translate("settingDialog", "谷歌浏览器路径"))
        self.recordPanel.setTitle(_translate("settingDialog", "电子实验系统"))
        self.consumablesPanel.setTitle(_translate("settingDialog", "耗材批号"))
        self.label_6.setText(_translate("settingDialog", "Protein A"))
        self.label_8.setText(_translate("settingDialog", "Protein A (AKTA)"))
        self.label_7.setText(_translate("settingDialog", "Ni-NTA"))
        self.label_9.setText(_translate("settingDialog", "Ni-NTA (AKTA)"))
        self.label_2.setText(_translate("settingDialog", "账号"))
        self.label_3.setText(_translate("settingDialog", "密码"))
        self.reagentPanel.setTitle(_translate("settingDialog", "试剂批号"))
        self.label_10.setText(_translate("settingDialog", "Buffer"))
        self.label_13.setText(_translate("settingDialog", "源数据"))
        self.srcpathLineEdit.setPlaceholderText(_translate("settingDialog", "F盘路径"))
        self.worktimePanel.setTitle(_translate("settingDialog", "工时系统"))
        self.label_5.setText(_translate("settingDialog", "密码"))
        self.label_11.setText(_translate("settingDialog", "上班时间"))
        self.label_4.setText(_translate("settingDialog", "账号"))
        self.label_12.setText(_translate("settingDialog", "下班时间"))
        self.pushButton.setText(_translate("settingDialog", "确定"))
        self.pushButton_2.setText(_translate("settingDialog", "取消"))
