# Form implementation generated from reading ui file 'taskDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_taskDialog(object):
    def setupUi(self, taskDialog):
        taskDialog.setObjectName("taskDialog")
        taskDialog.resize(408, 74)
        taskDialog.setStyleSheet("QFrame {\n"
                                 "    background-color: rgb(245, 245, 245);\n"
                                 "    border-radius: 5px;\n"
                                 "}\n"
                                 "QLabel {\n"
                                 "    color: rgb(60, 60, 60);\n"
                                 "}\n"
                                 "QProgressBar {\n"
                                 "    color: rgb(60, 60, 60);\n"
                                 "    background-color: rgb(230, 230, 230);\n"
                                 "    text-align: center;\n"
                                 "    border-radius: 8px;\n"
                                 "}\n"
                                 "QProgressBar:chunk {\n"
                                 "    background-color: rgb(126, 126, 126);\n"
                                 "    border-radius: 8px;\n"
                                 "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(taskDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=taskDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(taskDialog)
        QtCore.QMetaObject.connectSlotsByName(taskDialog)

    def retranslateUi(self, taskDialog):
        _translate = QtCore.QCoreApplication.translate
        taskDialog.setWindowTitle(_translate("taskDialog", "Dialog"))
        self.titleLabel.setText(_translate("taskDialog", "任务："))
